### ISSUE TITLE
TCA component for user logs

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#126]
Evaluate the need for a TCA friendly wrapper of a logging library.

We do have a minimal logger implemented from the ECC Reference wallet called Zealous Logger. 
https://github.com/zcash-hackworks/zealous-logger 

This logger is build around cocoa lumberjack.  The rationale behind it is that we want a logger that is transparent in its purpose, just plain old "print log statement to local_destination" no cloud service or any amenities whatsoever.

IIRC, the ECC Wallet used two rolling files of 1MB each. The user was able to "export" them via a share action sheet for troubleshooting purposes.

Update: [this article](https://swiftwithmajid.com/2022/04/19/exporting-data-from-unified-logging-system-in-swift) offers a good insight on leveraging OSLog for exporting instead of relying on a third party library.

**Comment by adamstener** [comment]
What logging framework should be used to manage logs?
What features are required for user logs?

Writing a wrapper that allows for easy mocking will not be difficult.  Defining what we need and working with something OSS or something built in to provide the required features is where the complexity will be for this ticket.

**Comment by steven-ecc** [comment]
@dh-ecc Any ideas? ^

**Comment by pacu** [comment]
updated description
