### ISSUE TITLE
Update validation successful screen to latest designs

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#139]
New successful screen
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/ea923a88-e541-4988-9a4e-775ba4e7e6f0)

https://xd.adobe.com/view/c058e090-8f05-4777-8370-d5ca819f931a-950b/screen/af0f0045-065b-47da-a944-0630a39614e6/specs/

things to update:
- Text content
- Text alignment
- Font Sizes
- Circular Image content

Check the screen looks ok on different font sizes and screen sizes.

**Comment by LukasKorba** [comment]
| iPhone 12 | iPhone SE |
| --- | --- |
| <img width="446" alt="Screenshot 2022-03-03 at 14 14 23" src="https://user-images.githubusercontent.com/7198042/156572016-1785cf78-65f2-437e-bc0e-90d911c2b67c.png"> | <img width="451" alt="Screenshot 2022-03-03 at 14 14 31" src="https://user-images.githubusercontent.com/7198042/156572029-7bbc8bad-3504-4da1-987c-8f9adb328224.png"> |
