### ISSUE TITLE
[UI Component] Custom Single line textfield

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#145]
**Requirements:**
- The textfield displays only a single line
- in the case of text has a middle  truncation mode
- allows to be titled
- the title can have an accessory view that performs an action
- the textfield allows one or more trailing accessory views
- the textfield can be provided with a validation function
- the textfield can display a caption/footer with relevant information about the current or future input
- the textfield can display a placeholder value that clears out when user input is detected

**Scoping questions**
Shall the title and its accessory view be left out of this component?

**Samples**

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/35676e65-7ced-4888-b8be-caea177be36b)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/7a1ecdb0-dc58-4e71-b498-586914cdada3)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/7fa3f6e3-d34b-4ac9-9880-131d551bb3bf)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/7fea7a76-4301-4b84-8b87-eda22c215a1f)
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/e425a9d5-a57d-4f11-8c55-7fb7979cab25)

**Comment by adamstener** [comment]
`allows to be Titled` Does this mean capitalized?
`the textfield can be provided with a validation function` Does this mean that something should be provided somewhere to display the valid and invalid states, given the parsing of the validation function?
`the textfield can display a caption/footer with relevant information about the current or future input` Do we have an example of the footer scenario? I'm assuming the header is provided here in the examples as the questions?
I don't see a requirement of the clear button
How do we truncate the header in the situation that it is too long or in the case that the clear button makes the message truncate?

**Comment by pacu** [comment]
> allows to be Titled Does this mean capitalized?
It means that you can add a title to the field if necessary. like "To:" or "Amount:" 

>the textfield can be provided with a validation function Does this mean that something should be provided somewhere to display the valid and invalid states, given the parsing of the validation function?

We don't have that on our current designs. The important part of this is that when you include this component in a form it lets you know whether the input is valid in this context or not so you can act accordingly. For example, disable the form's "proceed" button (or whatever its name is)

> I don't see a requirement of the clear button
I don't know if the clear button is part of the textfield or if is global to the screen. @geffenz could. you help us here?

> How do we truncate the header in the situation that it is too long or in the case that the clear button makes the message truncate?
good catch! Help @geffenz 🙏

> Do we have any examples of how this UI should adapt to changes in font size?
No, we don't. we should probably draft it at least in written.  @geffenz 

> Do we have an example of the footer scenario? I'm assuming the header is provided here in the examples as the questions?
I haven't seen any. Do we have that @geffenz ?

The ECC Wallet originally had a caption text that displayed some feedback depending on the input.
https://github.com/zcash/zcash-ios-wallet/blob/master/wallet/wallet/Components/ZcashTextField.swift


> There are two example designs here, and both look like they are dark modes. The size and color of the cursor changes between the two. Should the color and size be customizable to match these designs?
That's a @geffenz question 😅

**Comment by adamstener** [comment]
On the validation end, do we want open ended validation, like a regex the user can pass in, or do we want some sort of predefined list of validation things like `email` `phone number` etc.?

**Comment by adamstener** [comment]
On the clear button side of things, It looks like it his vertically centered on the header, but it appears that might cause issues if the Clear button is present and if the right accessory view is present.  The current designs only show this situation where the accessory view is text based and short in height, but the other examples of the accessory view there are taller images that are buttons.  I think these buttons will be far too close together for users to get right.  Thoughts?  Can you make an example?

**Comment by adamstener** [comment]
Does the clear button _always_ show whenever there is text present? Is this an option that can be turned on?

**Comment by adamstener** [comment]
Do we have any examples of the underline in the light color scheme?

**Comment by adamstener** [comment]
Any idea what the colors of the cursor will be in both light and dark mode? I see two different examples here in dark mode, and none for light.

**Comment by adamstener** [comment]
The previously linked implementation used AnyView for a footer, meaning anything could go into the footer at all.  However, since the view could be anything and doesn't tie into the state of the text field at all, this doesn't seem like it needs to be a part of this component and could instead just be vertically stacked with the text field input if needed.

**Comment by pacu** [comment]
Yes, as long as it fits the UI designs, I'm ok with that!

**Comment by adamstener** [comment]
> Yes, as long as it fits the UI designs, I'm ok with that!

I still don't have any examples of what this footer looks like, but referencing the old code it looks like it goes below the purple line, which should work just fine to be supplied _outside_ of this component.  Again, without a design it's hard to say for sure.

**Comment by pacu** [comment]
Thanks for pointing this out @adamstener, the footer will be in this case validation message (apparently)
@geffenz can you provide examples of what it would happen on invalid input for the address field and amount ? 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/484008/160139251-4197a439-954b-471a-b3d4-6c904e7d960a.png">
