### ISSUE TITLE
[UI Component] multiple line textfield

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#146]
**Requirements**
- It has a title text
- there's an accessory view next to the title
- the text input is aligned top left 
- the textview can be set up with a char limit
- when the char limit is set there's a char counter shown on the bottom trailing corner of the view with the format `char_count / char_limit`
- for the case that the char limit is modified by other external factors during the input, when reached either by typing or by changing the char limit, the textfield must display that the limit has been reached.
- TextViews with char limit shall have a validation value around that char limit, understanding that the char limit is a way of input validation. 
- TextView must never truncate any information. 

**Samples**
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/beefecfc-ccd2-46ea-8181-8c2c057ce100)

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/ab7713d6-4ad4-499e-aa82-1731c7f9541c)

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/5e8ca0b6-4024-46c5-b7d6-11ea26af6811)

**Comment by adamstener** [comment]
`for the case that the char limit is modified by other external factors during the input, when reached either by typing or by changing the char limit, the textfield must display that the limit has been reached.`
Do we have examples of what this display modification looks like other than the pictured current/limit footer?

**Comment by adamstener** [comment]
Is the text truncated at the tail if no limit is set but the available space is used?

**Comment by pacu** [comment]
The must never truncate information. 

updated the ticket with that info

**Comment by pacu** [comment]
There is an existing implementation of this here
https://github.com/zcash/zcash-ios-wallet/blob/master/wallet/wallet/Components/ZcashMemoTextField.swift

**Comment by geffenz** [comment]
Yeah, this looks correct. For clarity there is a "title header" above the input box, not a "title input textfield"!

**Comment by adamstener** [comment]
> Yeah, this looks correct. For clarity there is a "title header" above the input box, not a "title input textfield"!

So the biggest outstanding question is, if we accept a function for validation, and the text inputted is in fact invalid, what does the display look like at that point?

**Comment by adamstener** [comment]
If a text field should never truncate any info, but a char limit isn't set, should the text field stop taking input at some point? Should it scroll if there is no limit?

**Comment by pacu** [comment]
@geffenz 🙏
