### ISSUE TITLE
Broken Onboarding UI for .accessibilityLarge

### ISSUE THREAD

**Issue by LukasKorba** [zcash/secant-ios-wallet#179]
### Describe the issue
The Onboarding UI is broken for `.accessibilityLarge` setup.
<img width="376" alt="Screenshot 2022-02-28 at 10 31 36" src="https://user-images.githubusercontent.com/7198042/155959450-e984b492-8407-4398-bfde-18dbee9de188.png">

### Expected behaviour
There is no specific design provided that handles this accessibility setup. The goal is to render all necessary information with no overlaps. 

### Actual behaviour + errors
The UI uses ZStack and the Onboarding UI consists of 3 independent sections (header, content, footer). Those sections are rendered so they overlap.

- App Version: 0.0.1 (build 14)
- iOS Version: iOS 14+
- Device: any

**Comment by pacu** [comment]
A workaround is to use the `scrollableWhenScaledUp` modifier.

@geffenz would it be a problem if these views scroll up and down if they have bigger fonts?

**Comment by LukasKorba** [comment]
> A workaround is to use the `scrollableWhenScaledUp` modifier.

I'm aware of this modifier, I also used it to properly handle #165 but here the view structure is done composing 3 independent sections (header, content, footer) inside ZStack. The goal of the footer is always show the progress and buttons at the bottom of the screen. With large font, the central part of the screen is super small (iPhone SE) for the content = cirlular frame, caption and description. 

I think we will need to recreate the views so it's all in the VStack and `scrollableWhenScaledUp` will cause the buttons to be invisible at first sight. @geffenz

**Comment by pacu** [comment]
That's correct. scrollableWhenScaledUp is a workaround to let content be readable, but it's not intended to be a definitive solution to it.

**Comment by LukasKorba** [comment]
@geffenz we pretty much do the same, if the scale > 1 we put all the content to the scroll view. It's a workaround that works on most screens except this one for the following reasons:

# Complexity
The screen is composed of 3 independent components:
- Header (back/skip buttons)
- Content (circular frame + captions & paragraphs)
- Footer (primary/secondary buttons + steps progress)

These 3 sections are currently implemented relying heavily on ZStack, offsets and animations. All connected together. 
The ZStack is needed to deliver certain design requirements:
- back/skip buttons over the image (final step of the onboarding, independency over circular frame)
- action buttons + progress always at the bottom of the screen

`scrollableWhenScaledUp()` modifier is not working in the composition like this. The ZStack is breaking everything (see the picture at the initial description of the issue). 

# Conclusion
In order to properly rely on `scrollableWhenScaledUp()` the screen would have to be composed using VStack. Unfortunately that is affecting all components and the way how they behave and animate.

**Comment by LukasKorba** [comment]
result of a new composition of views:
| step 1 | step 2 | step 3 | final step |
| ------------- | ------------- | ------------- | ------------- |
| <img width="391" alt="Screenshot 2022-12-07 at 13 15 37" src="https://user-images.githubusercontent.com/7198042/206178821-7a497cc1-2f16-41ca-8b81-97b7648ac305.png"> | <img width="383" alt="Screenshot 2022-12-07 at 13 15 46" src="https://user-images.githubusercontent.com/7198042/206178849-1294a09e-b191-485b-ad50-e13c69ec9ccf.png"> | <img width="388" alt="Screenshot 2022-12-07 at 13 15 54" src="https://user-images.githubusercontent.com/7198042/206178880-ff86027c-7e30-4e4b-9cc5-39d1dae4487e.png"> |<img width="385" alt="Screenshot 2022-12-07 at 13 16 06" src="https://user-images.githubusercontent.com/7198042/206178901-0d633c08-8b36-4fb3-8754-fb470c124067.png"> |

reference from @geffenz:
![telegram-cloud-photo-size-4-5801913145567063938-w](https://user-images.githubusercontent.com/7198042/206179167-065a2371-f87d-45b6-9253-413c0d974758.jpg)
