### ISSUE TITLE
Code inconsistency

### ISSUE THREAD

**Issue by LukasKorba** [zcash/secant-ios-wallet#180]
# Introduction to the issue
There are couple of things I'd like to point out and get a clarification of `how to` moving forward. I assume the outcome of the discussion may be some code refactor so this issue will be used to pair it with potential ticket later.

# TCA files
Looks like the naming convention in the secant wallet is to use `<feature>View` for the View part of the TCA and `<feature>Store` for the `States/Actions/Environment/Reducers`. However I see some instances that are different, for example:
```
BackupFlow
> RecoveryPhraseDisplayStore

vs. 

> RecoveryPhraseValidation
```
The `RecoveryPhraseValidation` is clearly holding the same set of TCA code like in case of `RecoveryPhraseDisplayStore`. Another example is `Settings` in the Features folder. Settings.swift file is the TCA file with reducer, etc.

Also for some reason the static instances of stores are in the View files and I personally would expect it in the Store file. Example:

```swift
// file: RecoveryPhraseBackupValidationView.swift

extension RecoveryPhraseValidationStore {
    private static let scheduler = DispatchQueue.main

    static let demo = Store(
        initialState: .placeholder,
        reducer: .default,
        environment: .demo
    )
    ...
```
Thoughts?

# Features vs. Screens
Another inconsistency I see is the folders `Features` vs `Screens`. The Onboarding is currently (views) in the Screens folder while BackupFlow is all inside Features. Onboarding under the Folders is also present, the Store is there but Views is holding only placehoder view.

The Features folder look like a structure from the past with the following design:
```
<feature> main folder
   <feature>Store.swift // TCA
   Views folder
       ... // views for the feature
```
Which out of these 2 main folder are we going to use or how are we going to use both?

# Latest/newest TCA vs. "oldschool" one
(note: I briefly touched this topic with @dh-ecc, hence interested to find out way forward)
There is concept called `@BindableState/BindableAction` that is removing a lot of boilerplate. You can find out more info [here](https://pointfreeco.github.io/swift-composable-architecture/BindableState/). We can definitely use "oldschool" way and provide custom Binding, completely skip this new feature of the TCA. On the other hand I used it for example in upcoming #165, works nicely but I do want to follow agreed and consistent way.

Are we going to allow @BindableState/BindableAction? Thoughts?

# Store typealias
In most cases the store is typealiased and referring to the store is always done via this typealias. There are instances where this is not the case. Examples:
```swift
// typealias
struct AppView: View {
    let store: AppStore
struct ValidationSucceededView: View {
    var store: RecoveryPhraseValidationStore
struct ValidationFailedView: View {
    var store: RecoveryPhraseValidationStore
struct RecoveryPhraseBackupValidationView: View {
    let store: RecoveryPhraseValidationStore

// no typealias
struct HomeView: View {
    let store: Store<HomeState, HomeAction>
struct SendView: View {
    let store: Store<SendState, SendAction>
struct OnboardingHeaderView: View {
    let store: Store<ViewState, ViewAction>
struct OnboardingContentView: View {
    let store: Store<OnboardingState, OnboardingAction>
struct OnboardingFooterView: View {
    let store: Store<OnboardingState, OnboardingAction>
```
Thougths?

# Effect(...) vs. .init(...)
Here I'd like to double check the way forward is to always use Effect initialiser and never use .init instead. Basically any action (case) can return a side effect and that could be done as `return .init(value:`, also clearly visible when concatenating
```swift
return .concatenate(
.init(value...
.init(value...
.init(value...
)
```
I assume it's preferred to do it like this:
```swift
return .concatenate(
Effect(value...
Effect(value...
Effect(value...
)
```
agreed?

# Folders and subfolders
Probably the most complex feedback here is about ability to read the folders and files and get as close to expected structure and understanding of files as possible. When I tried to isolate backup validation phrase view/screen/feature I ended up with the following list of dependencies and files.
<img width="310" alt="Screenshot 2022-02-24 at 13 32 42" src="https://user-images.githubusercontent.com/7198042/155982058-7197893e-2995-42eb-9b43-73c1fac126c1.png">
It's been stated that you already discussed dependencies in the View. Seems like it's been agreed that we purpose expect any domino effect here so in reality, isolating 1 view can end up adding majority of all files/screens/and features to the separated module. I'm ok with it as long as we all agree. On the other hand when I tried to understand those dependencies by separating them in logical modules I ended up with the following structure:
<img width="317" alt="Screenshot 2022-02-28 at 13 14 51" src="https://user-images.githubusercontent.com/7198042/155982274-04ebdd2a-57a0-45c2-9cf9-3d2c4d637459.png">
My goal was to see at first sight what all files are related to the (isolated) feature - testing if user knows the seed phrase by drag and dropping chips to the right positions. Whoever is supposed to touch that screen, add or fix something, any newcomers or contributers should be able to get overview of those isolated screens.
Right now the backupFlow is:
<img width="326" alt="Screenshot 2022-02-28 at 13 21 19" src="https://user-images.githubusercontent.com/7198042/155982754-796a069d-8848-4dd8-9444-0431af64d7bd.png">
The thing is that inside Views folder, there are helper UI components alongside with completely standalone screens for the Validation either Success or Failure. The `BackupFlow` folder is helping me to understand that I can very likely expect more than just one screen. But it's not clear how many or what files are actually referring to it. So technically speaking I would expect to see something like this:
```
BackupFlow folder
     RecoveryPhraseBackupValidation folder
     ValidationFailedView folder
     ValidationSuccessView folder
     Views
         <helper UI components>
```
One last comment to the folders and subfolders. Right now, the backup flow uses Chips Views. `Phrase, Empty, Enumerated, Colored`. These 4 are currently under `UIComponents` but used only by BackupFlow. While `WordChipGrid` is under BackupFlow, also helper view for the flow only, consisted of composed Chips. My mind is trying to convince me these Chips and WordChipGrid should be in the same folder.

Thoughts?

# Conclusion
I'm interested to hear your thoughts and if we decide to shuffle or refactor things a bit, I can gladly help with all agreed changes.

@pacu @dh-ecc

**Comment by pacu** [comment]
> Looks like the naming convention in the secant wallet is to use <feature>View for the View part of the TCA and <feature>Store for the States/Actions/Environment/Reducers. However I see some instances that are different, for example:

I double checked pointfree's example projects and they don't seem to follow a general convention and they seem to have a per-example approach depending on whether they have UIKit and SwiftUI versions of the example or the granularity of the modularization.

On one hand, having the `FeatureName.swift` file name for Store is nice because is less redundant, shorter than having the `Store` suffix everywhere. On the other hand, suffixing filenames provides better and easier search results, but cutters the view tree.

Probably a future self will appreciate better code search results. If there are no objections we can go with that and suffix `Store` to States/Actions/Environment/Reducers and `View` to Views.

**Comment by pacu** [comment]
> Also for some reason the static instances of stores are in the View files and I personally would expect it in the Store file. 
>
> Example:
> 
> // file: RecoveryPhraseBackupValidationView.swift
> 
> extension RecoveryPhraseValidationStore {
>     private static let scheduler = DispatchQueue.main
> 
>     static let demo = Store(
>         initialState: .placeholder,
>         reducer: .default,
>         environment: .demo
>     )
>     ...
> Thoughts?

Where should we put code that is (at the moment) intended for Previews only? 
I think that we could move it elsewhere, maybe its own extension file like `FeatureStore+Demo.swift`?

**Comment by pacu** [comment]
> Store typealias
> In most cases the store is typealiased and referring to the store is always done via this typealias. There are instances where this is not the case. Examples:
> 
> // typealias
> struct AppView: View {
>     let store: AppStore
> struct ValidationSucceededView: View {
>     var store: RecoveryPhraseValidationStore
> struct ValidationFailedView: View {
>     var store: RecoveryPhraseValidationStore
> struct RecoveryPhraseBackupValidationView: View {
>     let store: RecoveryPhraseValidationStore
> 
> // no typealias
> struct HomeView: View {
>     let store: Store<HomeState, HomeAction>
> struct SendView: View {
>     let store: Store<SendState, SendAction>
> struct OnboardingHeaderView: View {
>     let store: Store<ViewState, ViewAction>
> struct OnboardingContentView: View {
>     let store: Store<OnboardingState, OnboardingAction>
> struct OnboardingFooterView: View {
>     let store: Store<OnboardingState, OnboardingAction>
> Thougths?

Except the Onboarding, the rest of the things you are mentioning are placeholder views that are yet to be replaced by their scaffold and then functional counterparts. I personally used typealiases to unclutter the code when referring to these Generic types from TCA.  
The reducer alias is the best example
`typealias RecoveryPhraseValidationReducer = Reducer<RecoveryPhraseValidationState, RecoveryPhraseValidationAction, BackupPhraseEnvironment>`

**Comment by pacu** [comment]
> Effect(...) vs. .init(...)
> Here I'd like to double check the way forward is to always use Effect initialiser and never use .init instead. Basically any action (case) can return a side effect and that could be done as return .init(value:, also clearly visible when concatenating
> 
> return .concatenate(
> .init(value...
> .init(value...
> .init(value...
> )
> I assume it's preferred to do it like this:
> 
> return .concatenate(
> Effect(value...
> Effect(value...
> Effect(value...
> )
> agreed?

Yes, I agree

**Comment by adamstener** [comment]
> > Also for some reason the static instances of stores are in the View files and I personally would expect it in the Store file.
> > Example:
> > // file: RecoveryPhraseBackupValidationView.swift
> > extension RecoveryPhraseValidationStore {
> > private static let scheduler = DispatchQueue.main
> > ```
> > static let demo = Store(
> >     initialState: .placeholder,
> >     reducer: .default,
> >     environment: .demo
> > )
> > ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thoughts?
> 
> Where should we put code that is (at the moment) intended for Previews only? I think that we could move it elsewhere, maybe its own extension file like `FeatureStore+Demo.swift`?
> 
> I'm thinking a few sprints ahead in terms of defining snapshot/screenshot testing or UI testing where we need to rely on these "demo" stores. They could probably grow up in number for LoC and clutter the files they are placed (either being Store or View)

Because these can be used in multiple places, I would think that static definitions of stores belong in the Store definition file.  One caveat to that though, is if you use a specific store definition for unit testing or UI testing, I think the definition of that store should belong in the testing file.

**Comment by adamstener** [comment]
> > Effect(...) vs. .init(...)
> > Here I'd like to double check the way forward is to always use Effect initialiser and never use .init instead. Basically any action (case) can return a side effect and that could be done as return .init(value:, also clearly visible when concatenating
> > return .concatenate(
> > .init(value...
> > .init(value...
> > .init(value...
> > )
> > I assume it's preferred to do it like this:
> > return .concatenate(
> > Effect(value...
> > Effect(value...
> > Effect(value...
> > )
> > agreed?
> 
> Yes, I agree

This is a broader topic than on the Effect type, and we should have a clear understanding documented of when it's ok to use the .init style intializer.  

In my opinion there are two things that matter most for this conversation:
readability and consistency.

I would expect that if you have two of these definitions together, they would use the same style.  i.e. you wouldn't place a .init next to a Effect(, that creates some misdirection in understanding what is going on.

The other is readability.  If it's hard for the reader to see what type is being initialized, then the fully qualified name should be used.  If it's obvious what type is being initialized, the brevity can win for readability sake, but again only if there is no lost context here.
An example:
```
func produceEffect() -> Effect {
    .init(data)
}
```

Because the return type is already specified right in the function signature, near the call site of the return line of code, it's mostly redundant to use the fully qualified name again.  That context being placed in the function signature provides the readability you need so the brevity can be a win, especially if the qualified name is long.

However, if there is no context near the call site, and using .init provides ambiguity, then it's generally considered a loss to not use the qualified name.

**Comment by adamstener** [comment]
> > Looks like the naming convention in the secant wallet is to use View for the View part of the TCA and Store for the States/Actions/Environment/Reducers. However I see some instances that are different, for example:
> 
> I double checked pointfree's example projects and they don't seem to follow a general convention and they seem to have a per-example approach depending on whether they have UIKit and SwiftUI versions of the example or the granularity of the modularization.
> 
> On one hand, having the `FeatureName.swift` file name for Store is nice because is less redundant, shorter than having the `Store` suffix everywhere. On the other hand, suffixing filenames provides better and easier search results, but cutters the view tree.
> 
> Probably a future self will appreciate better code search results. If there are no objections we can go with that and suffix `Store` to States/Actions/Environment/Reducers and `View` to Views.

+1 for suffixes and consistency.

**Comment by adamstener** [comment]
> > Store typealias
> > In most cases the store is typealiased and referring to the store is always done via this typealias. There are instances where this is not the case. Examples:
> > // typealias
> > struct AppView: View {
> > let store: AppStore
> > struct ValidationSucceededView: View {
> > var store: RecoveryPhraseValidationStore
> > struct ValidationFailedView: View {
> > var store: RecoveryPhraseValidationStore
> > struct RecoveryPhraseBackupValidationView: View {
> > let store: RecoveryPhraseValidationStore
> > // no typealias
> > struct HomeView: View {
> > let store: Store<HomeState, HomeAction>
> > struct SendView: View {
> > let store: Store<SendState, SendAction>
> > struct OnboardingHeaderView: View {
> > let store: Store<ViewState, ViewAction>
> > struct OnboardingContentView: View {
> > let store: Store<OnboardingState, OnboardingAction>
> > struct OnboardingFooterView: View {
> > let store: Store<OnboardingState, OnboardingAction>
> > Thougths?
> 
> Except the Onboarding, the rest of the things you are mentioning are placeholder views that are yet to be replaced by their scaffold and then functional counterparts. I personally used typealiases to unclutter the code when referring to these Generic types from TCA. The reducer alias is the best example `typealias RecoveryPhraseValidationReducer = Reducer<RecoveryPhraseValidationState, RecoveryPhraseValidationAction, BackupPhraseEnvironment>`
> 
> I certainly don't know if this is frown upon in TCA practices or it is indifferent.

If the type isn't too long, not having the typealias can make it easier to navigate the code and go to the action or state when clicking through the types.

**Comment by adamstener** [comment]
> Latest/newest TCA vs. "oldschool" one

I don't have a strong preference here, other than introducing another custom type annotation and data flow can be difficult to onboard into an already difficult concept.  I'm generally for TCA conveniences, as long as we aren't making it too difficult for new people to the framework to grok what's going on.

That being said, I'd defer to Pacu and his thoughts on if keeping the boilerplate and keeping the flow consistent, or using all the tools at our disposal and keeping things concise has a bigger win.

**Comment by adamstener** [comment]
> One last comment to the folders and subfolders. Right now, the backup flow uses Chips Views. Phrase, Empty, Enumerated, Colored. These 4 are currently under UIComponents but used only by BackupFlow. While WordChipGrid is under BackupFlow, also helper view for the flow only, consisted of composed Chips. My mind is trying to convince me these Chips and WordChipGrid should be in the same folder.

My opinion would be that feature or screen specific components should be in the feature or screen folder, whatever naming we use there.  If a UIComponent is built to be reused across screens or across features, then it should be in  a reusable place like UIComponents.

**Comment by pacu** [comment]
**On Folders and structure**

I think the ideal would be to have each feature to be as isolated from the rest. Yet, we have to decide what we consider that it would be "going too far". 

This thread covers some of the pains we are referring to and how other projects are dealing with them.
https://forums.swift.org/t/tca-ideal-file-structure-for-production-level-apps/38926

One of the forum comments makes a reference to this episode of pointfree.co on modularity https://www.pointfree.co/collections/composable-architecture/modularity

On paper, having separate SPM modules for each feature sounds like heaven. Clean separation of concern, fasted build times, independent testability. A dream come true.  But in reality could end up being a huge overhead mess where we won't get the benefits of the modularity because of our small team size and application size but we will get all the drawbacks of having more maintenance burden, etc. 

I think (not completely sure though) that meeting somewhere in the middle is the adequate thing to do in this case. Create a folder structure that creates a "soft" structural context while maintaining a single module. Then we can proceed further in terms of modularity when the situation requires is. 

Any thoughts?

**Comment by pacu** [comment]
> https://github.com/johnpatrickmorgan/TCACoordinators
> 
> Using something like this could help stay in middle ground while also getting better encapsulation.

This seems really interesting. There's an inherent risk this guy Morgan actually retiring and not maintaining this code anymore, something that happened to me with Stephen Celis's SQLite Swift a few months after we released the first version of the SDK. :-/

**Comment by LukasKorba** [comment]
my 2 cents..

> https://github.com/johnpatrickmorgan/TCACoordinators

I mentioned TCACoordinators on the interview with Pacu and Carter but I'm also not confident we should rely on yet another dependency, this is always 50:50, sometimes it's getting outdated and hard to maintain.. 

Plus you already mentioned, using all tools TCA is offering + new coming from time to time increases learning curve and reviewing the code as a contributor.. 

I think this is a trade of example.. we could get better structure of folders by sticking one more concept to learn and understand and rely on... I can't make this decision

**Comment by pacu** [comment]
> my 2 cents..
> 
> > https://github.com/johnpatrickmorgan/TCACoordinators
> 
> I mentioned TCACoordinators on the interview with Pacu and Carter but I'm also not confident we should rely on yet another dependency, this is always 50:50, sometimes it's getting outdated and hard to maintain..
> 
> Plus you already mentioned, using all tools TCA is offering + new coming from time to time increases learning curve and reviewing the code as a contributor..
> 
> I think this is a trade of example.. we could get better structure of folders by sticking one more concept to learn and understand and rely on... I can't make this decision

I'm least worried about this aspect. If so, we should add documentation on how we use these features that potentially add complexity. By documentation I mean, adding a real section with examples on our code, not just a link to another github

**Comment by pacu** [comment]
> I think this is a trade of example.. we could get better structure of folders by sticking one more concept to learn and understand and rely on... I can't make this decision

@LukasKorba given the feedback @adamstener and I have given out, can you propose folder structure that makes sense to you? 

Honestly, I have not worked on a TCA-powered project before so I have no take on overall structure, as long as it serves our goals :)

**Comment by pacu** [comment]
> That being said, I'd defer to Pacu and his thoughts on if keeping the boilerplate and keeping the flow consistent, or using all the tools at our disposal and keeping things concise has a bigger win.

@adamstener  I'm ok with bringing up tools that help us reducing boilerplate as long as we have certainty of their stability, reliability both in terms of code quality and OSS project health. Also as I said on another comment, that we should provide self-contained examples and guidelines on how and when we are using this tools so everyone can be on the same page and this doesn't end up being yet-another-thing-to-review on every PR.

**Comment by dh-ecc** [comment]
Some great discussions here so far!. I've added a 👍 reaction to give a "+1", which is to say, I would not say anything different to what's in the comment. I'll add any further comments I have once I can write them a bit more succintly than what I have floating in my head 😅.

**Comment by LukasKorba** [comment]
> @LukasKorba given the feedback @adamstener and I have given out, can you propose folder structure that makes sense to you?

I'll have this in mind and definitely try something
