### ISSUE TITLE
Loading Screen Scaffold and navigation

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#19]
Create a loading screen that serves as a buffer to load the keychain and figure out the actual first screen of the Application: (Welcome and Onboarding or Home ScreenA)

Our past experience with ECC Wallet is that when the application loads, it's possible that the keychain is not yet unlocked when the views are being set up. So it's important to create a buffer between app init from iOS to the real App Domain's loading. so that credentials can be accessed consistently and the wallet state can be determined. 

Criteria: 
- when the application loads, the LoadingScreen is created. 
- the loading screen queries the KeyStoring service and determines which of the 3 paths must be taken
  a. credentials are found calls `proceedsToHome` on router
  b. credentials are not found `proceedToWelcome` on router
  c. there's an error calls `failWithError` on router
- tests for these cases

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/d2304919-690d-47b7-a03c-5203e032b06e)
