### ISSUE TITLE
Launch/Splash Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#198]
Add static launch screen to the secant-application

@geffenz might have to help us out extract this with adobe XD

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/80fd20a1-3e20-48c2-826b-e739c120591a)

via: ![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/e1d0a9a7-eb13-4845-a81b-84fff42b754c)

**Comment by geffenz** [comment]
and zip bundle here : [Uploading... LoadingLogos.zip]

**Comment by pacu** [comment]
Thanks Geffen!

**Comment by LukasKorba** [comment]
@geffenz can you please create 1 px wide max height pdf with the gradient? Check the thread here https://stackoverflow.com/questions/25772862/ios-8-background-gradient-for-launch-screen-file

I assume we want that gradient on static welcome screen as well (@pacu). The fact it's static prevents us from making it in the code. It must be an "image"...
