### ISSUE TITLE
make Welcome Screen the first screen of the App

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#199]
When the app launches, the very first screen the user sees should be the welcome screen view.
this is beside #198 which is the static screen that the OS shows on launch while application loads and before the control is handed over from the OS to the App Delegate.

This is mainly to have a starting point where the app is fully loaded in memory and rendering a live view. It was the case on the previous ECC Wallet that keychain elements were not unlocked on`applicationDidFinishLaunching` and there was a race condition that left wallets in a bad state where the wallet logic couldn't find keys in a timely manner and it proceeded to a "create new/restore" when there were keys present

**Comment by LukasKorba** [comment]
FYI
Current state without touching the code:

The welcome is the first screen (not related to static launch screen), also not triggering wallet (keychain) check when appDidFinishedLaunching… 

I see 1 known issue
initially the transition from the welcome to the startup screen (back then treated as home screen) is no longer fadeout but instant blink (which is not the best UX)… the solution how to fix it is not obvious, I discussed options with Daniel and for now (maybe even for MVP) it’s better to not invest time in fix

I also see 1 potential issue:
the didFinishLaunching has been replaced by WelcomeScreen onAppear lifecycle moment, it’s not a substitute for viewDidLoad (UIKit) though.. I was googling how much we risk keychain could be failing or not fully ready with no clear answer. Solutions trying to replicate viewDidLoad are nasty ones, we don’t want any of it in our code.. I suggest to go with the current state, leave this ticket opened and gather some feedback, wait on some initial tests and users (internal)
