### ISSUE TITLE
Add Swiftlint, review guidelines

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#22]
As a Contributor I'd like to know what the code style and the review guidelines are, so that I can be more effective with my PRs

- [x] Add SwiftLint guide from https://github.com/raywenderlich/swift-style-guide/blob/master/
- [x] Add SwiftLint yml
- [x] Add Code Review Guidelines
- [x] add Pull request template that contains a checklist for both contributor(s) and reviewer(s)

Resources:
https://swift.org/documentation/api-design-guidelines/
https://google.github.io/eng-practices/review/reviewer/
https://zcash.readthedocs.io/en/latest/rtd_pages/development_guidelines.html

**Comment by adamstener** [comment]
Instead of CodeReview guidelines should this instead reference a development Style Guide and development Contributing guide that respectively reference the Swift Styles that this repo expects as well as any overall design or architecture related things that are expected?

**Comment by pacu** [comment]
This is some baseline to get input from everyone get feedback and iterate.
