### ISSUE TITLE
[Scaffold] Balance Breakdown

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#224]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/978e2b03-25ab-4224-b3c1-16a0556e1dcf)

**Comment by pacu** [comment]
This is missing latest blockheight on the upper right corner of the breakdown and the autoshielding threshold on the bottom right corner below the breakdown

**Comment by pacu** [comment]
![IMG_B0BDAE4A88D2-1.jpeg](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/d6b48580-4765-4990-bca7-beaea4c124fe)

**Comment by LukasKorba** [comment]
@pacu @geffenz I wanted to ask, in the design there are shielded + pending but reference wallet has shielded + transaprent. Which one is correct for the secant? I would assume transaprent instead of pending but rather double check it.

**Comment by geffenz** [comment]
A pending could be transparent or shielded but I'm not sure the designs
explicitly name them when grouped in the summary. It should actually have a
counter in case there are multiple tx confirming. Let me revisit the design
and get back to you.
