### ISSUE TITLE
[Scaffold] Home Screen Implementation

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#225]
Add scaffold element that represent the Home Screen

show the basic elements of the Synchronizer status with labels

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/c73069f0-c048-4c39-b389-7e61069572e3)

**Comment by geffenz** [comment]
A little explanation on the transactional history interactions.

Pressing "all", or dragging it up, or flicking it up would all make it enlarge to use the majority of real estate with a minimized balance view at the top.

![image](https://user-images.githubusercontent.com/47196503/163631259-388c8c58-edf8-4166-867e-d984e74ad463.png)

Swiping down or pressing latest would have the drawer animate back down.
