### ISSUE TITLE
[UX] User is taken by surprise by the phrase backup test

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#257]
he user should be shown the seed phrase if the tests takes it by surprise

I forgot about it myself, that I work on it every day, so I guess that probably users will be taken by surprise as well.

the message warning that there will be a test is really small and people might not read it, or don't understand that the phrase won't be shown again until the test is completed.

this was considered int the designs. I guess it is weird that you can’t see your recovery phrase again once you bump with the test. I assume that the intention is that the user does not cheat but, if you really want to do it right you have to force quit the app and start over and that's horrible UX.

The back button on the phrase test leads to this screen but there's no way of seeing the phrase again. 

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/94f424de-69b2-413f-a9f7-c53786880dbe)

**Comment by geffenz** [comment]
I've added a warning before "create new wallet" and a task in the user research script to get further feedback.
