### ISSUE TITLE
Advanced Routing: setting a route may vary depending on the originating context

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#285]
## Is your feature request related to a problem? Please describe.
There are parts of the application where the navigation is non-linear and context-dependent. For example, the Recovery Phrase Display screen has a "Finished" button. This button might mean different things depending what originated navigating to that screen to begin with:

When creating a new wallet, the user is directed to that screen so the phrase can be backed up before taking the backup verification test. After passing the test, the user can tap "show me my phrase again" and that redirects the user to the phrase display screen. In this other case the "finished" button means "I'm done checking my phrase, take me to the next screen whatever that is". Then the last case is that the user can access the seed at any time when going to back to that screen through the profile screen. In that case "finished" means navigate back to the profile screen.

This also applies to non-linear navigation triggered by "deep links/Universal Links". When the app processes a link, it might generate a new route, but finishing that task might involve taking the user to another screen, which in some cases might be the screen the app was in originally if the process was paused on background moments previous to opening that link

## Describe the solution you'd like
This discussion emerged on https://github.com/zcash/secant-ios-wallet/pull/282.
The proposed solution by @LukasKorba  is

yes, this is the answer I was looking for! 

> This is actually very interesting problem and a good catch. The solution here "works" and will very likely work for some time. You mentioned that "show me display again" can be accessed from profile screen. The code
> 
> ```swift
> if let storedWallet = try? environment.walletStorage.exportWallet(),
>                storedWallet.hasUserPassedPhraseBackupTest {
>                 state.route = .home
>             }
> ```
> 
> always returns user back to home as long as test has been passed. What if we want to go back to profile screen? Or any other screen. This opens a discussion how to handle MANY options in the TCA routing. The action
> 
> ```swift
> case .phraseDisplay(.finishedPressed):
> ```
> 
> is triggered when the button is pressed but it's not helping to determine "the next" route. I'm thinking we need some better way how to be able to decide the next route when this finished button is pressed. We very likely need to know the previous route so we can get some context.
> 
> What do you say if we reimplement the route so it is computed property and whenever newValue is set, we backup the previous one. Something like this:
> 
> ```swift
>     var prevRoute: Route?
>     var internalRoute: Route = .welcome
>     var route: Route {
>         get { internalRoute }
>         set {
>             prevRoute = internalRoute
>             internalRoute = newValue
>         }
>     }
> ```
> 
> Everything will work as is but we now have the information about the previous route, meaning we can react in the
> 
> ```swift
> case .phraseDisplay(.finishedPressed):
> ```
> 
> If prev was home, let's get back to home. If it was profile, let's get back to profile. If it was phraseValidation, it means user wanted to see the phrase again. If it was onboarding/create wallet, we need to trigger the test.
> 
> If you think the solution in this PR is good enough, consider this comment pointless and task is good to merge.

**Comment by LukasKorba** [comment]
1st part of the routing is done, I used exactly the same code I mentioned in the comment. So I hold previous route and use the context to decide the next one. The thing is that phrase display screen and finished button pressed lives in different "realms". 
The conflict happens only when phrase display screen is presented in the recovery flow.

Going to the phrase display screen from the profile is different flow and doesn't need previous route context because it's handled on the side of the Profile Screen while the first case is handled by Home Screen.

Deeplinking and non-linear navigation to be discussed between me and @pacu. We also need to define the URLs and params for the deeplinking.

**Comment by LukasKorba** [comment]
I decided to split the work on Advanced routing into 2 parts… the #1 PR is here https://github.com/zcash/secant-ios-wallet/pull/325

for the deeplinking we can go different routes and the decision is depending on the scope and functionality we expect from the feature. We have basically several options:
1. TCACoordinators https://github.com/johnpatrickmorgan/TCACoordinators - If we decide for this, we will spend some time bending the current app to it
2. Custom stack (inspiration here https://johnpatrickmorgan.github.io/2021/07/03/NStack/).. something smaller than TCACoordinators but enough for the functionality we need, it also need some non-trivial time
3. If the deeplink is overwriting the app’s state and we don’t need to restore it, we can do only simple app route settings/updates.. I propose to create a dependency DeeplinkManager responsible for analysing the universal link and creating the particular AppState with the nested states needed to achive the screen and then override the current AppState
