### ISSUE TITLE
Import Wallet does not have a Birthday input field

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#301]
![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/7ccfa6c3-bb12-44c6-8426-4b282bca1f88)

Wallet import should have a Birthday height input field to make scanning faster. But there isn't one.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/bc7acac7-6b47-437f-a35e-367d4cfaae9a)

And viewable here : https://xd.adobe.com/view/631202e7-3efa-4528-bc39-155ab5f4c374-3641/
