### ISSUE TITLE
Blocking TODOs, Enhancements and Fixes

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#372]
This epic tracks any issue that blocks v1.0.0 release that falls under the following categories
- enhancements
- bugs and their fixes
- maintenance tasks
- CI / CD tasks

**Comment by LukasKorba** [comment]
This issue is no longer valid, refers to a state of secant in the past and a potential release that's never happened. Meanwhile secant became Zashi, new design, new plan, new epic/tickets to cover it.
