### ISSUE TITLE
Welcome and Onboarding Scaffold

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#4]
- [x] Screen elements on B&W that show an image, title, blurb and step
- [x] previous, next, close and skip buttons
- [x] Connect to navigation

previous should show when current step is > 0, 
next should show when 0 < current step < N, 
closed should be shown on the last step,
skip should be shown 0 < current step < N - 1

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/e5dd5060-051d-4e9b-8bbe-f7855fb552ef)

**Comment by geffenz** [comment]
This may be more complex as there are a few flows not hinted at with just this screen. Onboarding technically includes:
Loading, Welcome [education], restore/new options, seed backup for new (+verification), import seed/privkey/vkey.
