### ISSUE TITLE
4/10th Screen Action Sheet

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#40]
Screen name: Walkthrough - done

Create a screen overlay that overlaps the given proportion from the bottom of the screen which can accommodate a view and show the upper part of the screen as a 'background'

out of scope:
- presentation animations

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/9092ae86-7cc8-4643-b3f1-805a400dc147)
