### ISSUE TITLE
Warn the user about not enough available free space 

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#427]
Syncing takes a significant amount of space. We are working towards fixing that. Until then, we want to let users know that we don't consider there's enough space to continue syncing.
The goal is to not let the wallet paint itself to a corner and be proactive towards detecting this denial-of-service situation where the wallet occupies space that can't be claimed back.

Scenario:
When the app goes to foreground it will attempt to sync. Before doing so, the wallet should check whether there's enough space to continue safely.

use case A: there's enough space. the wallet proceeds to start syncing.

use case B: theres is **not** enough space. The wallet should not proceed to sync.  Instead it should show a warning as the design below.

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/8fd1170e-d3ee-49a1-b741-314459168a7a)

Preconditions: 
- this free space check happens only after the users has created a new wallet and backed up the keys successfully or restored from backup. 

implementation details:
- the amount of space required should be easily modifiable on code. 
- create mocks to trigger this scenario
- add snapshot test with the corresponding screenshot.
- implement light and dark mode.

**Comment by Chlup** [comment]
I implemented what is requested in this issue. I am just not sure if this logic will work in all cases. It will probably in case of full sync. This is just some food for thoughts how to improve this check.

But for example in this case it probably won't work:
- User has 2 GB of free space on device and user does full sync on Monday.
- On Tuesday user has only 500 MB of free space and runs the app. Now app says there isn't enough space. But user just needs to sync blocks mined only in last 24 hours. And 500 MB is probably enough for that. So in this case app does false positive detection of not enough free disk space.

**Comment by pacu** [comment]
This is a really good insight @Chlup.  

@ccjernigan shall the wallet estimate by linearly multiplying a size per block  by the delta between birthday and latest height?

**Comment by ccjernigan** [comment]
How can we keep this really simple?

The amount of disk usage will decrease in a few weeks when we move to storing blocks as files and doing download/scan in parallel.  That reduces the disk space needed, thus making the size difference between states that @Chlup points out much smaller.  I think this sort of solves itself at that time.

I think we can document this limitation and circle back once the SDK changes are made.
