### ISSUE TITLE
Seed Backup Flow

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#44]
After the onboarding flow, the user selects "create new wallet".

This action entails that the a new random 24-word  BIP-39 compliant Mnemonic Seed Phrase is created for the user.

The user must be able to Backup the seed phrase and subsequently validate the backed up words against some sort of challenge.

**Comment by nuttycom** [comment]
Nit: rename "Seed phrase" to "Emergency Recovery Phrase" everywhere.
