### ISSUE TITLE
Ensure that sensitive information can't be logged intentionally or by accident

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#444]
see `Undescribable` protocol on SDK 0.17.0-alpha

We need to ensure that types holding users' keys and addresses can't be picked up by crash reporters or event trackers and put into logs.

This should be made as inobstrusive and simply as possible. It must cover Mirroring APIs and plain description ( e.g: `String(describing:)`).

**Comment by LukasKorba** [comment]
I'll leave it here so anybody else can review as well.
Redacted so far:
- WalletStorage's seedPhrase and birthday
- ImportWalletReducer's state variables - seedPhrase and birthday
- create wallet action - chips

**Comment by LukasKorba** [comment]
another batch:
- wallet balances are redacted
- wallet events (transaction history) is redacted
- input fields for the send flow (zec user wants to send) is redacted as well as 'to' address
