### ISSUE TITLE
Verify Your backup

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#47]
Given an unverified seed phrase, the user must perform an action so that we can attest that the words have been backed up or noted somewhere.

The user is presented a grid with 4 words in a blue button-like element that are missing from the seed phrase below.

On the bottom part of the screen the seed phrase initially show on the previous screen now lacks 4 random chips, one from each visual group

- [x] the user must drag and drop all 4 of them in their corresponding places
- [x] there is no feedback until all words have been placed 
- [x] On success the flow navigates to the success screen 

On failure:
- [ ] Screen shakes and device vibrates half second.
- [ ] Animations revert
- [x] The screen is refreshed. the user must be presented 4 different words from each group to avoid guessing. (@geffen please validate this)

**Comment by geffenz** [comment]
https://xd.adobe.com/view/c058e090-8f05-4777-8370-d5ca819f931a-950b/

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/be48d22e-d64e-46ed-9d1c-6d7b8392f0ec)

**Comment by geffenz** [comment]
This is PR # 134.
