### ISSUE TITLE
[Scaffold] Seed phrase backup Success Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#48]
When the user successfully validates the seed, this screen shows up

- [x] Success title
- [x] backup to safe place subtitle
- [x] Circular Image with Shield Icon 
- [x] Primary Button ' Take Me to my wallet' proceeds to home screen 
- [x] Secondary button show my seed phrase again, displays a modal screen that shows the seed phrase again (@geffenz please validate this)

- [x] supports both dark and light mode

**Comment by geffenz** [comment]
Here is the XD link with the final assets. However, there has been no optimization done to these raster images (just in layer crops) so there will need to be a design delivery ticket.
