### ISSUE TITLE
Rename `AppStore` to avoid conceptual confusions 

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#495]
TCA Store for the Application called`AppStore` conceptually clashes with the Apple AppStore. 

let's rename it RootStore

**Comment by Niravprajapati1** [comment]
Can i work on this issue

**Comment by pacu** [comment]
Hello @Niravprajapati1 ! And welcome to Zcash! 🎉

**Comment by Niravprajapati1** [comment]
In which file ?

**Comment by Chlup** [comment]
`ApStore.swift`. This typealias: `typealias AppStore = Store<AppReducer.State, AppReducer.Action>`
