### ISSUE TITLE
Define and implement logs on a secant's side

### ISSUE THREAD

**Issue by LukasKorba** [zcash/secant-ios-wallet#524]
The work on #126 and #125 resulted in 3 different logs being present in the realm.
1. TCA logger - already gathering all actions and state changes
2. SDK logger - passed to the SDK, so also gathering logs from the SDK
3. Wallet logger - implemented but not reporting anything

Let's talk about what we want to log on a secant's side. Some proposal:
- app's lifecycle (started, go to bcg and go back from it, etc.)
- some user actions? button clicks etc? (Partially covered by TCA logs via .updateDestination action but we could pair it with real interactions and expected TCA counterparts)
- memory warnings

**Comment by pacu** [comment]
What we need to log:
1- User's whereabouts in the application. mainly to know who the application's lifecycle might be affecting the SDK
2- is in reality 1a. with an addition of issue #444. We want to know what the use is doing, not the content of the interactions
3- System warnings and other misc. errors are always useful.

ECC Wallet originally used a 2MB log consisting of two rolling log files of 1MB each. I think that's quite a lot. We might not need that much.
