### ISSUE TITLE
Flaky navigation issue

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#537]
Navigation stack resets

from home screen:
go to profile
then to address details and tap `back`
then go to settings

result: The app resets the navigation 
expected: the app shows settings

follow up: Navigation stays broken. user can't  go to the profile when it resets. It goes to some of the previously opened screens and back

**Comment by LukasKorba** [comment]
I tried main and the navigation looks fine there so I also switched to `add_crash_reporter` branch and for some reason that one works for me as well. I'm parking the work unless we figure out easy way how to reproduce the issue.
