### ISSUE TITLE
Add transaction details as standalone screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#565]

**Comment by LukasKorba** [comment]
I changed the transaction details screen, simplified it for all 4 types (sent, pending, received, failed)

![Simulator Screen Shot - iPhone 14 Pro - 2023-02-25 at 18 18 46](https://user-images.githubusercontent.com/7198042/221370617-766161b0-1ee6-41a0-aaf6-c87f68ce9c32.png)
