### ISSUE TITLE
Suggestion how to improve work with localisation

### ISSUE THREAD

**Issue by Chlup** [zcash/secant-ios-wallet#618]
For example let's have this localisation file:
```
"welcomeScreen.title" = "Powered by Zcash";
"welcomeScreen.subtitle" = "Subtitle for screen %@";
```

Currently when we want to use localisation we simply use the key from localisation file like this: `Text("welcomeScreen.title")`.
And when there is localisation string with parameters we have to manually handle it. Helper function for this was added in #603.

But still using raw localisation keys in the code can lead to typos and mistakes. And it's super hard to manage what is localised. And if the localisation keys used in the code are still in localisation file (and vice versa). There is no compilation time check for this.

**What is the suggestion?**
My suggestion is to generate structure like this:
```
enum L10n {
    enum welcomeScreen {
        static let title = L10n.loc("Localizable", "welcomeScreen.title", fallback: "Powered by Zcash")
        static func subtitle(_ p1: Any) -> String {
            return L10n.loc("Localizable", "welcomeScreen.subtitle", String(describing: p1), fallback: "Subtitle for screen %@")
        }
    }
}

extension L10n {
    private static func loc(_ table: String, _ key: String, _ args: CVarArg..., fallback value: String) -> String {
        let format = Bundle.main.localizedString(forKey: key, value: value, table: table)
        return String(format: format, locale: Locale.current, arguments: args)
    }
}
```

Then in the code when we want to use localisation we do this: `Text(L10n.welcomeScreen.title)` or this: `Text(L10n.welcomeScreen.subtitle("screen1"))`.

Structure like this must be automatically generated from localisable file. Localisable file is source of truth for localisation strings. And thanks to this we have compile time check if we are using valid localisations. 

**How to generate this structure?**
We could probably use some tool like `sourcery` to generate it. But maybe best solution would be to write our own super simple parser/generator/validator. Localisable strings file has simple format. And we could built in checks into tool like this. For example it could check for missing semicolons or it could compare multiple localisation files. This should make our life much easier when it comes to handle localisation. Or maybe we can check if there isn't any tool ready. There probably will be but it will have more functions than we need. And it will miss some that we need.

**Comment by pacu** [comment]
I think this is a good Idea.

We already use SwiftGen for colors. This can be done with that as well. 

https://itnext.io/why-you-should-strongly-type-your-localizations-with-swiftgen-340e35e7b6a3

**Comment by str4d** [comment]
If you're going to move away from the default Android localization system to a custom-built generator, I would recommend considering https://projectfluent.org/ as a base. It is built around the idea of "developers and localizers agree on an identifier for each string", for the same reason as you say above, and so you could likely generate similar structures to what you outlined above for use inside Kotlin.

The existing generators I've used for it in Rust have compile time checking of string existence and parameters, which could probably be replicated in Kotlin (maybe using https://github.com/projectfluent/fluent-kotlin for parsing and traversal).

**Comment by Chlup** [comment]
I talk about iOS app here. For now I used SwiftGen. It's super fast to use. It doesn't have any validation abilities but it gives us compile time check for localisation. And it just generations data structure which is easy to use for us but inside it is still using iOS built-in localisation system.

**Comment by ccjernigan** [comment]
We also don't plan on moving away from the standard Android system.
