### ISSUE TITLE
[Scaffold] Profile Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#73]
This includes a few design areas:

1. Main UA QR
2. Primary Action (See address details)
3. Secondary Actions

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/74e7ca18-7261-4bd2-bea0-c970891b60aa)

**Comment by geffenz** [comment]
Don't forget you can get to the XD docs here : https://docs.google.com/document/d/1S6qPFL4D48vRYIbXHOoGdiJvE_5xN11ufjSOk-MZiTo/edit
