### ISSUE TITLE
DX: UserDefaultsInterface wraps a non-asynchronous method call in an asynchronous context

### ISSUE THREAD

**Issue by tw0po1nt** [zcash/secant-ios-wallet#743]
## What were you trying to do
Access the UserDefaults dependency from one of our app's views

## What happened
During implementation, I noticed that the `UserDefaultsInterface` needlessly wraps some non-asynchronous methods in an asynchronous context:

```
struct UserDefaultsClient {
    let objectForKey: @Sendable (String) -> Any?
    let remove: @Sendable (String) async -> Void
    let setValue: @Sendable (Any?, String) async -> Void
    let synchronize: @Sendable () async -> Bool
}
```

I could maybe understand the need or desire for this if there were any asynchronous code running to augment access into `UserDefaults`, but no such code exists. It is purely a TCA wrapper:
```
static func live(userDefaults: UserDefaults = .standard) -> Self {
        Self(
            objectForKey: { userDefaults.object(forKey: $0) },
            remove: { userDefaults.removeObject(forKey: $0) },
            setValue: { userDefaults.set($0, forKey: $1) },
            synchronize: { userDefaults.synchronize() }
        )
    }
```

With no added benefit and the burden of having to wrap these calls in an async context to use them properly, I think this API should be changed to be synchronous, just like the underlying UserDefaults API is.

Additionally, synchronize should be removed, as [per Apple's documentation](https://developer.apple.com/documentation/foundation/userdefaults/1414005-synchronize), it does nothing and they discourage its use.

**Comment by LukasKorba** [comment]
Even though pointfree guys do exactly the same (except the synchronize) I agree we should simplify the interface. Will be done in coming days as part of secant's modularization into packages.
