### ISSUE TITLE
[Scaffold] Settings Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#75]
As A user I would like to access a settings screen so that I can change some aspects of the user experience and perform different maintenance/unusual actions. 

Acceptance criteria:
- there's a Theme changing switch
- fiat conversion on/off switch
- a nuke button that, upon confirmation of the action (with an alert dialog) allows the user to delete all wallet data (credentials, logs, caches, data, etc) and close the application
  - the nuke button does not raise a crash in the crash reporting tool
- backup wallet that shows the secret recovery phrase (requires authentication)
- ~security pin (removing it requires the input of the pin)~
- ~All action buttons require PIN if the pin is enabled.~
- a rescan wallet button that upon confirmation on alert dialog, uses the rewind API on the SDK to rescan the wallet

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/88d03740-addb-42ba-b45c-bef4c2b440dd)

https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/
