### ISSUE TITLE
[Functional] Profile Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#76]
Acceptance criteria
  - Unified Address QR code
  - a text that is trimmed in the middle of the same address which can be copied to clipboard with a tap
  - a primary action button that takes the user to address details
  - address book button (not for MVP)
  - a secondary action button that takes the user to the settings screen
  - a separator line 
  - Coinholder Vote button (disabled)
  - a support button that opens an email URI so that the user can send an email to the application's support email.
  - application name and version that can be copied to clipboard when tapped and  yellow see log application logs button that leads to a log reader screen
  
  
  ![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/7aa19d3a-1ea6-4d35-9d6f-208c684b6263)

https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/

**Comment by geffenz** [comment]
https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/fd60ce57-0728-455b-ae42-ec4de621f4b2)
