### ISSUE TITLE
[Functional] Settings Screen

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#78]
As A user I would like to access a settings screen so that I can change some aspects of the user experience and perform different maintenance/unusual actions. 

Acceptance criteria:
- there's a Theme changing switch
- fiat conversion on/off switch
- a nuke button that, upon confirmation of the action (with an alert dialog) allows the user to delete all wallet data (credentials, logs, caches, data, etc) and close the application
  - the nuke button does not raise a crash in the crash reporting tool
- backup wallet that shows the secret recovery phrase (requires authentication)
- security pin (removing it requires the input of the pin)
- All action buttons require PIN if the pin is enabled.
- a rescan wallet button that upon confirmation on alert dialog, uses the rewind API on the SDK to rescan the wallet

**Comment by geffenz** [comment]
As a first step, can we add a toggle for changing theme from light to dark so UI can be tweaked? This would be functional so I am listing it here, but not the complete ticket.

**Comment by adamstener** [comment]
There currently is no notion of light and dark themes in the app, that differ from the users global settings for the device.  If we want the user to be able to select light and dark through a setting, we would first have to build theming that does not rely on the users device setting.

**Comment by geffenz** [comment]
Ok, this may be my ignorance then. If I can change the theme in the OS this request is not needed. Thank you!

**Comment by geffenz** [comment]
https://xd.adobe.com/view/68ce275c-cab9-42da-9679-08501e961790-3d9d/

![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/b852f775-d0d7-49c9-a405-885baa21adab)
