### ISSUE TITLE
Core BTS UI: Load Screen

### ISSUE THREAD

**Issue by nuttycom** [zcash/secant-ios-wallet#802]
Update the loading screen to a transition between the following views:

- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4814&mode=design&t=9FayedV7L5uAZNyV-1 
- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4551&mode=design&t=9FayedV7L5uAZNyV-1 
- [ ] https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=88%3A4443&mode=design&t=9FayedV7L5uAZNyV-1

**Comment by LukasKorba** [comment]
The transition is the background that goes from the bottom to the top.
<img width="1237" alt="Screenshot 2023-08-21 at 8 46 31" src="https://github.com/zcash/secant-ios-wallet/assets/7198042/b9f257f7-8d84-4b14-9193-085853617f6b">

Things to have in mind:
- there's a launch screen, I suggest to leave it dark with "HI" and the logo
- once the launch screen is dismissed, the WelcomeView (see the module Welcome) takes the control
- it's a very simple UI that stays on screen for 3 seconds, replacing the launch screen for now with the same design
- the view with the `create new wallet` and `restore existing wallet` is actually PlainOnboardingView in the OnboardingFlow module
- the Zashi supports both light and dark appearances so the transition needs to work both ways
- the buttons in Zashi use viewModifiers, you can find it in UIComponents module, for now only `activeButtonStyle`. This one needs to be updated according to the designs.. as you can see the design has reversed colours button, it could be either a new viewModifier or a parameter,. something like.. .activeButtonStyle(reversedColours: true)

**Comment by LukasKorba** [comment]
Resolved in #836
