### ISSUE TITLE
Core BTS UI: Recovery Phrase Screen

### ISSUE THREAD

**Issue by nuttycom** [zcash/secant-ios-wallet#803]
Update the recovery phrase screen to conform to https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-branding-ADJY-MOCK?type=design&node-id=148%3A6122&mode=design&t=9FayedV7L5uAZNyV-1

**Comment by LukasKorba** [comment]
| a | a |
| === | === |
| a | a |

<img width="342" alt="Screenshot 2023-08-21 at 8 56 18" src="https://github.com/zcash/secant-ios-wallet/assets/7198042/ac75cd2c-f443-4054-8dd4-bd3011ec4335">

**Comment by LukasKorba** [comment]
resolved in #848
