### ISSUE TITLE
Core BTS UI: Transactions Screen

### ISSUE THREAD

**Issue by nuttycom** [zcash/secant-ios-wallet#809]
Update the transactions listing screen to conform to https://www.figma.com/file/vYQD6uZtkPgtmgJ3zfauq0/Zashi-UI-082123-V3?type=design&node-id=148%3A7956&mode=design&t=MuSYkgngwcFg2nNl-1

**Comment by LukasKorba** [comment]
| current version | expected version |
| --- | --- |
| ![Simulator Screenshot - iPhone 14 Pro - 2023-08-22 at 08 18 20](https://github.com/zcash/secant-ios-wallet/assets/7198042/207e2b17-93ea-41b4-9a67-ae0c732f5905) | <img width="331" alt="Screenshot 2023-08-22 at 8 17 56" src="https://github.com/zcash/secant-ios-wallet/assets/7198042/192c9b57-5f6e-4e6f-ab5c-133d660fcf75"> |

```swift
        case paid(success: Bool)
        case received
        case failed
        case sending
        case receiving
```

- There are 5 possible states the transactions can end up with, so have this in mind
- `send to <address>` is possible and such row is just about restyling and updating the layout
- `received` (notice received to typo) at the moment is without the address, we don't have such information so write only received and don't bother with from <address>
- In similar way update `sending to` and `receiving` states
- failed transaction lacks the design, @nuttycom 
- lastly, the balance is not present in the current implementation of this screen so it must be added, please follow the same principle present in Home (Features/Home) or Send (Features/SendFlow) screens, both implements the logic how to listen to the balance updates, render shielded balance

**Comment by nuttycom** [comment]
I'm closing this issue temporarily; there is work underway to move transaction history to the home screen in the Figma designs.
