### ISSUE TITLE
[Functional] Sending Screen - Success

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#88]
Edit:

As | I would like to | So that
-- | -- | --
user | see the progress of an outgoing transaction | I can know what's going on and what to expect
user | see success screen after transaction has been submitted | I can have feedback of my payment and see more details about it

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/dc6b7f1e-94d2-405f-9303-ad049091e533)

**Comment by Chlup** [comment]
I think that there is nothing more to do for this ticket. Both required user stories are already implemented and working.
