### ISSUE TITLE
Profile Screen Navigation Placeholder

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#9]
Contains a Screen that is shown as a placeholder for the real contents for navigational purposes. 
This screen lets developers test that the navigation proposed can be properly implemented and that the user can transition between the screens that precede and follow this one. 
 
Contains mocked elements that demonstrate the nature of the screen and UI elements that allow the user to perform navigation actions

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/fbe7a0bd-d988-41f4-8164-1e95b40fc1d6)
