### ISSUE TITLE
[Scaffold] Received Transaction Details 

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#96]
As a User I would like to see the details available for a given transaction:

- Date Created (format YYYY-mm-dd hh:mm a) (time is local time)
- Tx minedHeight or "unconfirmed"
- transaction id
- value amount
- Fee
- From / to address
- memo (if available)
  - reply-to compliance
- confirmations
- total amount

Items that can be copied to clipboard:
- memo
- from / to address
- transaction ID

Reference: (look and feel not needed on this story)

![image.png](https://images.zenhubusercontent.com/5dc33e54c84ceb0001835974/710f5e69-10ee-449b-b87f-f4ae5e025c55)

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/e7fc3587-a0c5-4edc-bc0a-f53963ea8c73)

**Comment by pacu** [comment]
@geffenz Note that the screenshots you included are for transaction history, not details.

**Comment by geffenz** [comment]
Thanks @pacu - I deleted the comment and here is the correct image: 
![image](https://user-images.githubusercontent.com/47196503/147130704-3e36c8f7-1ba8-49ff-a603-1f499852c1c8.png)

This is usable for scaffolding, but there will be some differences for the functional ticket.

**Comment by pacu** [comment]
Notes: See view `ScreenOverlay` on this url  https://github.com/zcash/zcash-ios-wallet/blob/master/wallet/wallet/Views/Feedback/FeedbackDialog.swift

**Comment by pacu** [comment]
@geffenz We are missing the transaction id.
