### ISSUE TITLE
[Scaffold] Full Wallet History

### ISSUE THREAD

**Issue by pacu** [zcash/secant-ios-wallet#98]
objectives:

The main objective is to show the users the (un-styled) information available for them in their wallet history.

Although the underpinnings of the data layer on the SDK are not defined yet we can Identify certain events or transactions

- Received ZEC (confirmed or pending)
- Sent ZEC (confirmed or pending)
- Transactions that failed to send (failed pending)
- Autoshielding transactions
- Shielded Pool migration transaction (from sapling to orchard)

User stories:

| As   | I would like to                                                                  | So that                                                                        |
|------|----------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| user | see most recent transactions without leaving my home screen                      | so that I can see latest activity in a glance                                  |
| user | see my whole known history                                                       | so that I can inspect the past transactions involving my keys                  |
| user | see failed transactions                                                          | I can be aware transactions that failed to send                                |
| user | see shield by default transactions                                               | I can keep track of how my wallet has been keeping my funds private            |
| user | see pool migration transactions                                                  | I can keep track of how my wallet has been keeping in the latest shielded pool |
| user | see transactions containing a payment request in the memo as a "payment request" | so that I can quickly attempt to fulfill it if funds available                 |
| user | see transactions that have memos with zero-value as messages                     | I can be aware that there's probably an important memo in that tx              |

Things that remain undefined for now:
- standardized logic to identify autoshielding transactions
- standardized logic to identify pool migration transactions
- "Wallet import" event 
- Whether the history will allow users to see filtered views of their history

Out of Scope:
- definitions of such undefined items above. Please use placeholder functions or variables to mock the appearance until that logic is defined.
- pagination support
- detection of autoshielding or pool migration on real transactions. 

Other Limitations:
the SDK doesn't provide the data needed to show the information to the user on:
- Autoshielding
- pool migration
- previously used outgoing transactions.
- fiat conversion at the time of the transaction
- statistics on accounted ZEC value shielded from transparent address

Those should be mocked and left as placeholders as well.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/11d0d525-4450-4331-99f5-7ba71c3de5b8)

Here are the layout rough drafts. I will create an interaction spec for the rows and detail flow next.

**Comment by geffenz** [comment]
Wallet History (links updated in Google Doc)
https://docs.google.com/document/d/1S6qPFL4D48vRYIbXHOoGdiJvE_5xN11ufjSOk-MZiTo/edit

https://xd.adobe.com/view/5178a3e0-013d-4534-bb1a-20bc19cedcd7-042b/

**Comment by pacu** [comment]
@geffenz are we going to add filters to the transaction history?

**Comment by geffenz** [comment]
We had removed filters for MVP, but I would consider it likely in the
future ( transparent, shielded, memo, receive, send ). If tje.level.of
effort is low I can create comps!
